// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWO4j4FwxAvWT5qb0S180dK2Cyex_iiTI',
    appId: '1:951794221378:web:2aab094a9f0782b78d48db',
    messagingSenderId: '951794221378',
    projectId: 'flood-detection-6299c',
    authDomain: 'flood-detection-6299c.firebaseapp.com',
    databaseURL: 'https://flood-detection-6299c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flood-detection-6299c.firebasestorage.app',
    measurementId: 'G-70RJPNRF2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFS2KduxYqJzAjUvc9KPWA-cUdij-lLJk',
    appId: '1:951794221378:android:bc74f7291e2ceabf8d48db',
    messagingSenderId: '951794221378',
    projectId: 'flood-detection-6299c',
    databaseURL: 'https://flood-detection-6299c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flood-detection-6299c.firebasestorage.app',
  );
}
